### ISSUE TITLE
Can we add param parsing?

### ISSUE THREAD

**Issue by vvscode** [FGRibreau/npm-interactive-scripts#4]
Running `ns test` and get script ran with fuzzy-search value to `test` might be nice 

Also ready provide a PR =)

**Comment by FGRibreau** [comment]
I did not understand your suggestion, could you please give an example?

**Comment by vvscode** [comment]
Sure

running `ns test` should open the script, with prefilled `test` in fuzzy-search and display filtered items from script

it might be useful if I do remember a part of the script name. Currently scenario is
- run `ns`
- type `test`
- choose item

will be 
- run `ns test`
- choose item

**Comment by vvscode** [comment]
![screencast 2020-12-07 08-41-43](https://user-images.githubusercontent.com/6904368/101317951-8b549180-3870-11eb-88d1-facc7817c93e.gif)

**Comment by FGRibreau** [comment]
Great idea @vvscode, I will accept a PR for that :)
